version: '3.6'

volumes:
  gateway_modules:
  Registration_modules:

services:
  gateway:
    build: 
      context: .
      dockerfile: ./BackEnd/Gateway/Dockerfile.dev
    volumes:
      - ./BackEnd/Gateway:/Gateway
      - gateway_modules:/Gateway/node_modules
    ports:
      - '3001:3000'
      - '9229:9229'
    depends_on:
      - registration
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_COGNITO_POOLID=${AWS_COGNITO_POOLID}
      - BUCKET_NAME=${BUCKET}
      - REGISTRATION_SERVICE=http://registration:3000
      - STAGE=dev
  
  registration:
    build: 
      context: .
      dockerfile: ./BackEnd/Registrations/Dockerfile.dev
    volumes:
      - ./BackEnd/Registrations:/Registrations
      - Registration_modules:/Registrations/node_modules
    ports:
      - '3002:3000'
      - '9230:9229'
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - STAGE=dev