FROM node:carbon

ARG NPM_TOKEN

RUN echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

RUN yarn global add gulp
RUN yarn add gulp

WORKDIR /Gateway
ADD ./BackEnd/Gateway/package.json /Gateway/package.json

RUN yarn install

CMD ["yarn", "start"]