FROM node:carbon

ARG NPM_TOKEN

RUN echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

RUN yarn global add gulp
RUN yarn add gulp

WORKDIR /Registrations
ADD ./BackEnd/Registrations/package.json /Registrations/package.json

RUN yarn install

CMD ["yarn", "start"]